# This rule is not used by the project polyfea-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to polyfea.github.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: polyfea-controller
    app.kubernetes.io/managed-by: kustomize
  name: microfrontendclass-viewer-role
rules:
- apiGroups:
  - polyfea.github.io
  resources:
  - microfrontendclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - polyfea.github.io
  resources:
  - microfrontendclasses/status
  verbs:
  - get
