apiVersion: polyfea.github.io.polyfea.github.io/v1alpha1
kind: MicroFrontend
metadata:
  labels:
    app.kubernetes.io/name: polyfea-controller
    app.kubernetes.io/managed-by: kustomize
  name: microfrontend-sample
spec:
  # TODO(user): Add fields here
